name: AZ Voting App Redis CI/CD Pipeline
trigger:
- master

resources:
- repo: self

variables:
- template: templates/variables/vars.yaml 

pool:
  name: az-selfhosted

stages:
- template: templates/stages/ci.yaml
- template: templates/stages/cd.yaml