name: AZ Voting App Redis CI/CD Pipeline
trigger:
- master

resources:
- repo: self

variables:
- template: templates/variables/vars.yml 

pool:
  name: az-selfhosted

stages:
- template: templates/stages/ci.yml
- template: templates/stages/cd.yml